### ISSUE TITLE
isna() doesn't seem to work in @where statement

### ISSUE THREAD

**Issue by mwsohn** [davidanthoff/Query.jl#118]
In general, it would be very nice if Query.jl provides an easy functionality by which NA values are removed from a DataFrame.

**Comment by davidanthoff** [comment]
You need to use ``isnull`` in queries instead of ``isna``.

Queries is using its own type ``DataValue`` to represent missing values, so even if you start with something like a ``DataFrame``, missing values will be represented as an instance of ``DataValue`` inside the query. I would actually prefer to use ``isna`` for ``DataValue``s, but right now I can't do that without taking a dependency on DataArrays, which I don't want to do. So until I come up with some other way, you'll have to use ``isnull``..

> In general, it would be very nice if Query.jl provides an easy functionality by which NA values are removed from a DataFrame.

I assume you are looking for an easy way to remove rows that have missing values? The next version of Query (which will only work on julia 0.6) should enable something like this
````julia
@where !any(isnull.(i))
````
here you apply the ``isnull`` function to all columns of the source using the dot vectorization syntax from base, and then you make sure there are no ``true``s returned. Would that address your need? Please let me know if it doesn't, or if you think this is too clumsy etc. I'm really looking for feedback on these design issues to make sure the package ends up working for folks!

**Comment by mwsohn** [comment]
That would be great. isnull also works well. Thank you.
